name: what_to_do
description: A new Flutter project.
publish_to: 'none'


version: 1.0.7+14

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  provider: ^6.0.5
  intl: ^0.18.1
  sqflite: ^2.3.0
  path: ^1.8.3
  package_info_plus: ^4.1.0
  flutter_email_sender: ^6.0.2
  device_info: ^2.0.3
  shared_preferences: ^2.2.2
  info_popup: ^4.1.0
  icloud_storage: ^2.2.0
  path_provider: ^2.1.1
  flutter_slidable: ^3.0.1
  flutter_native_splash: ^2.3.8
  http: ^1.1.2
  home_widget: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/


  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 600
